### ISSUE TITLE
SyntaxError: Invalid regular expression flags

### ISSUE THREAD

**Issue by carlosefonseca** [Ashung/svg2vectordrawable#10]
Just installed and tried to use it and:

```
❯❯❯ s2v -i file.svg
/usr/local/lib/node_modules/svg2vectordrawable/lib/coa.js:60
            if (/^<.*>$/s.test(val.trim())) {
                ^

SyntaxError: Invalid regular expression flags
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:588:28)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/svg2vectordrawable/bin/svg2vectordrawable:3:1)
```

Actually not even `s2v -h` works.

**Comment by carlosefonseca** [comment]
I just removed the `s` in `/^<.*>$/s` and it works ¯\_(ツ)_/¯

**Comment by Ashung** [comment]
What's your node.js version. I test in v8.11.4 and v9.11.1.
