### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by TobiasReich** [Ashung/svg2vectordrawable#42]
So we discovered several small issues - **I guess we should make a pull request for you**.

### First of all there are error messages like this one:

```
TypeError: Cannot read property 'value' of undefined
    at childPaths.forEach.item (/node_modules/svg2vectordrawable/lib/svg-to-vectordrawable.js:134:78)
    at Array.forEach (<anonymous>)
    at elemGroups.forEach.elem (/node_modules/svg2vectordrawable/lib/svg-to-vectordrawable.js:131:28)
    at Array.forEach (<anonymous>)
    at JS2XML.refactorData (/node_modules/svg2vectordrawable/lib/svg-to-vectordrawable.js:128:20)
    at JS2XML.convert (/node_modules/svg2vectordrawable/lib/svg-to-vectordrawable.js:604:10)
    at data (/node_modules/svg2vectordrawable/lib/svg-to-vectordrawable.js:741:40)
    at SAXParser.sax.onend (/node_modules/svgo/lib/svgo/svg2js.js:169:13)
    at emit (/node_modules/sax/lib/sax.js:624:35)
    at end (/node_modules/sax/lib/sax.js:667:5)
```

So we replaced line
`if (!elem.hasAttr('fill', 'none') && !item.hasAttr('fill', 'none')) {`
with 
`if (elem.attr('fill') && !elem.hasAttr('fill', 'none') && !item.hasAttr('fill', 'none')) {`
essentially skipping broken elements

### Also:

in line 737 the error check is referencing the wrong property. Instead of

```
if (data.err) {
   reject(data.err);
}
```

it should be

```
if (data.error) {
   reject(data.error);
}
```

otherwise I get that error:

```
TypeError: data.querySelectorAll is not a function
    at JS2XML.refactorData (/node_modules/svg2vectordrawable/lib/svg-to-vectordrawable.js:90:28)
    at JS2XML.convert (/node_modules/svg2vectordrawable/lib/svg-to-vectordrawable.js:604:10)
    at data (/node_modules/svg2vectordrawable/lib/svg-to-vectordrawable.js:741:40)
    at module.exports (/node_modules/svgo/lib/svgo/svg2js.js:179:9)
    at Promise (/node_modules/svg2vectordrawable/lib/svg-to-vectordrawable.js:736:9)
    at new Promise (<anonymous>)
    at module.exports (/node_modules/svg2vectordrawable/lib/svg-to-vectordrawable.js:735:12)
```

### Last but not least there are some type errors:

```
TypeError: Cannot read property 'elem' of null
TypeError: Cannot read property 'elem' of null
    at elemUses.forEach.elem (/node_modules/svg2vectordrawable/lib/svg-to-vectordrawable.js:254:62)
    at Array.forEach (<anonymous>)
    at JS2XML.refactorData (/node_modules/svg2vectordrawable/lib/svg-to-vectordrawable.js:251:18)
    at JS2XML.convert (/node_modules/svg2vectordrawable/lib/svg-to-vectordrawable.js:604:10)
    at data (/node_modules/svg2vectordrawable/lib/svg-to-vectordrawable.js:741:40)
    at SAXParser.sax.onend (/node_modules/svgo/lib/svgo/svg2js.js:169:13)
    at emit (/node_modules/sax/lib/sax.js:624:35)
    at end (/node_modules/sax/lib/sax.js:667:5)
```

The problem seemed to come from that code:

```
// Tag use to original
    let elemUses = data.querySelectorAll('use');
    if (elemUses) {
        elemUses.forEach(elem => {
            if (elem.hasAttr('xlink:href')) {
                let originalElem = data.querySelector(elem.attr('xlink:href').value);
                let newElem = new JSAPI({ elem: originalElem.elem });
                elem.eachAttr(attr => {
                    if (attr.name !== 'xlink:href' && attr.name !== 'id') {
                        newElem.addAttr(attr);
                    }
                });
                originalElem.eachAttr(attr => {
                    if (attr.name !== 'xlink:href' && attr.name !== 'id') {
                        newElem.addAttr(attr);
                    }
                });
                elem.parentNode.spliceContent(elem.parentNode.content.indexOf(elem), 0, newElem);
                elem.parentNode.spliceContent(elem.parentNode.content.indexOf(elem), 1, []);
            }
        });
    }
```

Which couldn't find a link in the svg. However at this position it was applied at the Android xml drawable already so the link was missing. We moved it from line 248ff. to an earlier stage at line 90.  There it uses the svg xml and seems to successfully  work.

**Comment by Ashung** [comment]
Thank you.
